name: django app deploy's workflow 

on:
  push:
    branches: [main]    

jobs:
  deploy:  
    runs-on: ubuntu-latest
    steps:
      - name: clone the code 
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: build image 
        run: docker build -t robertolandry/ci-cd_django_app  .


      - name: push image to Docker Hub
        run: docker push robertolandry/ci-cd_django_app:latest 


            

